version: '3.1'

services:
  db:
    container_name: MongoDB
    image: mongo:6.0.3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
     - 27017:27017
  app:
    depends_on:
      - db
    container_name: Backend
    build:
      context: .
      target: ${STAGE}
      dockerfile: Dockerfile
      
      # command: yarn start:dev
    volumes:
        - .:/home/node/app
        - /home/node/app/node_modules
    ports:
      - ${PORT}:${PORT}
    environment:
      PORT: ${PORT}
      HOST: ${HOST}
    restart: always