version: '3.1'

services:
  db:
    container_name: ${DB_HOST}
    image: mongo:6.0.3
    restart: always
    volumes:
      - mongo-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    #ports:
    #  - ${DB_PORT}:${DB_PORT}
  backend:
    depends_on:
      - db
    container_name: Backend
    build:
      context: .
      target: ${STAGE}
      dockerfile: ./Dockerfile
    volumes:
        - .:/app/
        - /app/node_modules
        - /app/dist
    ports:
      - ${PORT}:${PORT}
    environment:
      PORT: ${PORT}
      HOST: ${HOST}
      DB_HOST: ${DB_HOST}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      DB_PROTOCOL: ${DB_PROTOCOL}
      DB_URL: ${DB_URL}
    restart: always
  frontend:
    depends_on:
      - backend
    container_name: Frontend
    build:
      context: .
      target: ${STAGE}
      dockerfile: ../frontend-schedule-control/Dockerfile
    volumes:
      - ../frontend-schedule-control/:/app/
    ports:
      - 3000:3000
    environment:
      WATCHPACK_POLLING: true
      REACT_APP_API_URL: ${REACT_APP_API_URL}
    restart: always
volumes:
  mongo-db:
    external: true
    